var app = angular.module('myApp', []);
var listProductObject = [
	{id:"1", name:"Leather Black M", price:"$159.00", 
	href_product:"Product_ForHer/product_forher_1.html",
	images:"images/her-1/her-1.png", type:"healthy"},
	{id:"2", name:"Melin Tregwynt Elements S", price:"$139.00", 
	href_product:"Product_ForHer/product_forher_2.html",
	images:"images/her-2/her-2.png", type:"healthy"},
	{id:"3", name:"Melin Tregwynt Halo S", price:"$139.00", 
	href_product:"Product_ForHer/product_forher_3.html",
	images:"images/her-3/her-3.png", type:"healthy"},
	{id:"4", name:"Expedition Atlantic Blue", price:"$115.00", 
	href_product:"Product_ForHer/product_forher_4.html",
	images:"images/her-4/her-4.png", type:"healthy"},
	{id:"5", name:"Expedition Black", price:"$115.00", 
	href_product:"Product_ForHer/product_forher_5.html",
	images:"images/her-5/her-5.png", type:"healthy"},
	//chanel
	{id:"7", name:"Braun Chanel black leather handbag shoulder bag chain", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_chanel/product_forbrand_7.html",
	images:"../ForBrand/images/women/brand-chanel/brand-1/brand-1.jpg", type:"chanel"},
	{id:"8", name:"Braun Chanel black leather shoulder bag chain", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_chanel/product_forbrand_8.html",
	images:"../ForBrand/images/women/brand-chanel/brand-2/brand-2.jpg", type:"chanel"},
	{id:"9", name:"Brown Chanel Black Shoulder Bag Handbag", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_chanel/product_forbrand_9.html",
	images:"../ForBrand/images/women/brand-chanel/brand-3/brand-3.jpg", type:"chanel"},
	{id:"10", name:"Braun Chanel black caviar leather handbag", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_chanel/product_forbrand_10.html",
	images:"../ForBrand/images/women/brand-chanel/brand-4/brand-4.jpg", type:"chanel"},
	{id:"11", name:"Fashion Chanel Women's Black Diamond Lattice Handbag", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_chanel/product_forbrand_11.html",
	images:"../ForBrand/images/women/brand-chanel/brand-5/brand-5.jpg", type:"chanel"},
	{id:"12", name:"Braun Chanel black Satchel Handbag", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_chanel/product_forbrand_12.html",
	images:"../ForBrand/images/women/brand-chanel/brand-6/brand-6.jpg", type:"chanel"},
	
	//lv
	{id:"13", name:"YesMacton cowskin Genuine Leather Women", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_lv/product_forbrand_13.html",
	images:"../ForBrand/images/women/brand-lv/brand-1/brand-1.jpg", type:"lv"},
	{id:"14", name:"Monogram Canvas Sarah Wallet", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_lv/product_forbrand_14.html",
	images:"../ForBrand/images/women/brand-lv/brand-2/brand-2.jpg", type:"lv"},
	{id:"15", name:"Leather Accents Classic Boston Bag", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_lv/product_forbrand_15.html",
	images:"../ForBrand/images/women/brand-lv/brand-3/brand-3.jpg", type:"lv"},
	{id:"16", name:"Sharon Monogram Canvas Palm Springs Backpack Mini Handbag", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_lv/product_forbrand_16.html",
	images:"../ForBrand/images/women/brand-lv/brand-4/brand-4.jpg", type:"lv"},
	{id:"17", name:"FairyBridal Women Real Leather Cross Body Handbags", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_lv/product_forbrand_17.html",
	images:"../ForBrand/images/women/brand-lv/brand-5/brand-5.jpg", type:"lv"},
	{id:"18", name:"Ceyue Women's Drawstring Handbag Bucket Bags Shoulder Backpack", price:"$115.00", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_lv/product_forbrand_18.html",
	images:"../ForBrand/images/women/brand-lv/brand-6/brand-6.jpg", type:"lv"}
]
app.controller('myCtrl', function($scope) {
    $scope.products = listProductObject;
});