var app = angular.module('myApp', []);
var listProductObject = [
	{id:"1", name:"Great Outdoors Olive M", price:"$65.00", 
	href_product:"Product_ForHim/product_forhim_1.html",
	images:"images/him-1/him-1.png", type:"healthy"},
	{id:"2", name:"Ground Cover Navy Tan M", price:"$65.00", 
	href_product:"Product_ForHim/product_forhim_2.html",
	images:"images/him-2/him-2.png", type:"healthy"},
	{id:"3", name:"Microfibre Black M", price:"$65.00", href_product:"Product_ForHim/product_forhim_3.html",
	images:"images/him-3/him-3.png", type:"healthy"},
	{id:"4", name:"Textured Nylon Periwinkle Big Bag", price:"$65.00", 
	href_product:"Product_ForHim/product_forhim_4.html",
	images:"images/him-4/him-4.png", type:"healthy"},
	{id:"5", name:"Urban Traveller Dark Teal M", price:"$65.00", 
	href_product:"Product_ForHim/product_forhim_5.html",
	images:"images/him-5/him-5.png", type:"healthy"},
	{id:"6", name:"Urban Traveller Tuscan Red M", price:"$65.00", 
	href_product:"Product_ForHim/product_forhim_6.html",
	images:"images/him-6/him-6.png", type:"healthy"},
	//nike
	{id:"7", name:"NIKE SPORT", price:"$85", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_nike/product_forbrand_7.html",
	images:"../ForBrand/images/men/brand-nike/brand-1/brand-1.jpg", type:"nike"},
	{id:"8", name:"NIKE BRASILIA", price:"$55", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_nike/product_forbrand_8.html",
	images:"../ForBrand/images/men/brand-nike/brand-2/brand-2.jpg", type:"nike"},
	{id:"9", name:"NIKE BRASILIA MEDIUM", price:"$45", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_nike/product_forbrand_9.html",
	images:"../ForBrand/images/men/brand-nike/brand-3/brand-3.jpg", type:"nike"},
	{id:"10", name:"NIKE HOOPS ELITE MAX AIR TEAM 2.0", price:"$85", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_nike/product_forbrand_10.html",
	images:"../ForBrand/images/men/brand-nike/brand-4/brand-4.jpg", type:"nike"},
	{id:"11", name:"NIKE SPORT  DUFFEL BAG", price:"$45", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_nike/product_forbrand_11.html",
	images:"../ForBrand/images/men/brand-nike/brand-5/brand-5.jpg", type:"nike"},
	{id:"12", name:"NIKE LIGHTWEIGHT", price:"$110", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_nike/product_forbrand_12.html",
	images:"../ForBrand/images/men/brand-nike/brand-6/brand-6.jpg", type:"nike"},
	//addidas
	{id:"13", name:"Gym Bag with Shoe Compartment Men Duffel Bag, Medium", price:"$268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_addidas/product_forbrand_13.html",
	images:"../ForBrand/images/men/brand-addidas/brand-1/brand-1.jpg", type:"addidas"},
	{id:"14", name:"Sports Gym Bag Travel Duffel Bag", price:"$268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_addidas/product_forbrand_14.html",
	images:"../ForBrand/images/men/brand-addidas/brand-2/brand-2.jpg", type:"addidas"},
	{id:"15", name:"Canvas Fabric Gym Bag Sports Duffels Athletic Sport Shoulder Bag", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_addidas/product_forbrand_15.html",
	images:"../ForBrand/images/men/brand-addidas/brand-3/brand-3.jpg", type:"addidas"},
	{id:"16", name:"Adidas Defender II Duffel Bag", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_addidas/product_forbrand_16.html",
	images:"../ForBrand/images/men/brand-addidas/brand-4/brand-4.jpg", type:"addidas"},
	{id:"17", name:"Adidas Alliance II Sackpack", price:"$ 268.99", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_addidas/product_forbrand_17.html",
	images:"../ForBrand/images/men/brand-addidas/brand-5/brand-5.jpg", type:"addidas"},
	{id:"18", name:"Adidas Diablo Small Duffle Bag", price:"$115.00", 
	href_product:"../ForBrand/Product_ForBrand/product_forbrand_addidas/product_forbrand_18.html",
	images:"../ForBrand/images/men/brand-addidas/brand-6/brand-6.jpg", type:"addidas"}
]
app.controller('myCtrl', function($scope) {
    $scope.products = listProductObject;
});