var app = angular.module('myApp', []);
var listProductObject = [
	// Bobby brand
	{id:"1", name:"Bobby compact anti-theft backpack, pastel blue", 
		price:"$94.95",
		href_product:"Product_ForBrand/product_forbrand_bobby/product_forbrand_1.html",
		images:"images/bobby/brand-1/brand-1.jpg", type:"bobby"},
	{id:"2", name:"Bobby compact anti-theft backpack, coralette", price:"$94.95",
	href_product:"Product_ForBrand/product_forbrand_bobby/product_forbrand_2.html",
	images:"images/bobby/brand-2/brand-2.jpg", type: "bobby"},
	{id:"3", name:"Bobby compact anti-theft backpack, diver blue", price:"$94.95",
	href_product:"Product_ForBrand/product_forbrand_bobby/product_forbrand_3.html",
	images:"images/bobby/brand-3/brand-3.jpg", type:"bobby"},
	{id:"4", name:"Bobby compact anti-theft backpack, primrose yellow", price:"$94.95",
	href_product:"Product_ForBrand/product_forbrand_bobby/product_forbrand_4.html",
	images:"images/bobby/brand-4/brand-4.jpg", type:"bobby"},
	{id:"5", name:"Bobby anti-theft backpack, black", price:"$89.95",
	href_product:"Product_ForBrand/product_forbrand_bobby/product_forbrand_5.html",
	images:"images/bobby/brand-5/brand-5.jpg", type:"bobby"},
	{id:"6", name:"Bobby anti-theft backpack, grey", price:"$89.95",
	href_product:"Product_ForBrand/product_forbrand_bobby/product_forbrand_6.html",
	images:"images/bobby/brand-6/brand-6.jpg", type:"bobby"},
	
	//Healthy
	{id:"1", name:"Great Outdoors Olive M", price:"$65.00", 
	href_product:"../ForHim/Product_ForHim/product_forhim_1.html",
	images:"../ForHim/images/him-1/him-1.png", type:"healthy"},
	{id:"2", name:"Ground Cover Navy Tan M", price:"$65.00", 
	href_product:"../ForHim/Product_ForHim/product_forhim_2.html",
	images:"../ForHim/images/him-2/him-2.png", type:"healthy"},
	{id:"3", name:"Microfibre Black M", price:"$65.00", 
	href_product:"../ForHim/Product_ForHim/product_forhim_3.html",
	images:"../ForHim/images/him-3/him-3.png", type:"healthy"},
	{id:"4", name:"Textured Nylon Periwinkle Big Bag", price:"$65.00", 
	href_product:"../ForHim/Product_ForHim/product_forhim_4.html",
	images:"../ForHim/images/him-4/him-4.png", type:"healthy"},
	{id:"5", name:"Urban Traveller Dark Teal M", price:"$65.00", 
	href_product:"../ForHim/Product_ForHim/product_forhim_5.html",
	images:"../ForHim/images/him-5/him-5.png", type:"healthy"},
	{id:"6", name:"Urban Traveller Tuscan Red M", price:"$65.00", 
	href_product:"../ForHim/Product_ForHim/product_forhim_6.html",
	images:"../ForHim/images/him-6/him-6.png", type:"healthy"},
	
	//Nike
	{id:"7", name:"NIKE SPORT", price:"$85", 
	href_product:"Product_ForBrand/product_forbrand_nike/product_forbrand_7.html",
	images:"images/men/brand-nike/brand-1/brand-1.jpg", type:"nike"},
	{id:"8", name:"NIKE BRASILIA", price:"$55", 
	href_product:"Product_ForBrand/product_forbrand_nike/product_forbrand_8.html",
	images:"images/men/brand-nike/brand-2/brand-2.jpg", type:"nike"},
	{id:"9", name:"NIKE BRASILIA MEDIUM", price:"$45", 
	href_product:"Product_ForBrand/product_forbrand_nike/product_forbrand_9.html",
	images:"images/men/brand-nike/brand-3/brand-3.jpg", type:"nike"},
	{id:"10", name:"NIKE HOOPS ELITE MAX AIR TEAM 2.0", price:"$85", 
	href_product:"Product_ForBrand/product_forbrand_nike/product_forbrand_10.html",
	images:"images/men/brand-nike/brand-4/brand-4.jpg", type:"nike"},
	{id:"11", name:"NIKE SPORT  DUFFEL BAG", price:"$45", 
	href_product:"Product_ForBrand/product_forbrand_nike/product_forbrand_11.html",
	images:"images/men/brand-nike/brand-5/brand-5.jpg", type:"nike"},
	{id:"12", name:"NIKE LIGHTWEIGHT", price:"$110", 
	href_product:"Product_ForBrand/product_forbrand_nike/product_forbrand_12.html",
	images:"images/men/brand-nike/brand-6/brand-6.jpg", type:"nike"},
	
	//addidas
	{id:"13", name:"Gym Bag with Shoe Compartment Men Duffel Bag, Medium", price:"$268.99", 
	href_product:"Product_ForBrand/product_forbrand_addidas/product_forbrand_13.html",
	images:"images/men/brand-addidas/brand-1/brand-1.jpg", type:"addidas"},
	{id:"14", name:"Sports Gym Bag Travel Duffel Bag", price:"$268.99", 
	href_product:"Product_ForBrand/product_forbrand_addidas/product_forbrand_14.html",
	images:"images/men/brand-addidas/brand-2/brand-2.jpg", type:"addidas"},
	{id:"15", name:"Canvas Fabric Gym Bag Sports Duffels Athletic Sport Shoulder Bag", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_addidas/product_forbrand_15.html",
	images:"images/men/brand-addidas/brand-3/brand-3.jpg", type:"addidas"},
	{id:"16", name:"Adidas Defender II Duffel Bag", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_addidas/product_forbrand_16.html",
	images:"images/men/brand-addidas/brand-4/brand-4.jpg", type:"addidas"},
	{id:"17", name:"Adidas Alliance II Sackpack", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_addidas/product_forbrand_17.html",
	images:"images/men/brand-addidas/brand-5/brand-5.jpg", type:"addidas"},
	{id:"18", name:"Adidas Diablo Small Duffle Bag", price:"$115.00", 
	href_product:"Product_ForBrand/product_forbrand_addidas/product_forbrand_18.html",
	images:"images/men/brand-addidas/brand-6/brand-6.jpg", type:"addidas"},
	
	//healthy
	{id:"1", name:"Leather Black M", price:"$159.00", 
	href_product:"../ForHer/Product_ForHer/product_forher_1.html",
	images:"../ForHer/images/her-1/her-1.png", type:"healthy"},
	{id:"2", name:"Melin Tregwynt Elements S", price:"$139.00", 
	href_product:"../ForHer/Product_ForHer/product_forher_2.html",
	images:"../ForHer/images/her-2/her-2.png", type:"healthy"},
	{id:"3", name:"Melin Tregwynt Halo S", price:"$139.00", 
	href_product:"../ForHer/Product_ForHer/product_forher_3.html",
	images:"../ForHer/images/her-3/her-3.png", type:"healthy"},
	{id:"4", name:"Expedition Atlantic Blue", price:"$115.00", 
	href_product:"../ForHer/Product_ForHer/product_forher_4.html",
	images:"../ForHer/images/her-4/her-4.png", type:"healthy"},
	{id:"5", name:"Expedition Black", price:"$115.00", 
	href_product:"../ForHer/Product_ForHer/product_forher_5.html",
	images:"../ForHer/images/her-5/her-5.png", type:"healthy"},
	{id:"6", name:"Expedition Burgundy", price:"$115.00", 
	href_product:"../ForHer/Product_ForHer/product_forher_6.html",
	images:"../ForHer/images/her-6/her-6.png", type:"healthy"},
	
	//chanel
	{id:"7", name:"Braun Chanel black leather handbag shoulder bag chain", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_chanel/product_forbrand_7.html",
	images:"../ForBrand/images/women/brand-chanel/brand-1/brand-1.jpg", type:"chanel"},
	{id:"8", name:"Braun Chanel black leather shoulder bag chain", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_chanel/product_forbrand_8.html",
	images:"../ForBrand/images/women/brand-chanel/brand-2/brand-2.jpg", type:"chanel"},
	{id:"9", name:"Brown Chanel Black Shoulder Bag Handbag", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_chanel/product_forbrand_9.html",
	images:"../ForBrand/images/women/brand-chanel/brand-3/brand-3.jpg", type:"chanel"},
	{id:"10", name:"Braun Chanel black caviar leather handbag", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_chanel/product_forbrand_10.html",
	images:"../ForBrand/images/women/brand-chanel/brand-4/brand-4.jpg", type:"chanel"},
	{id:"11", name:"Fashion Chanel Women's Black Diamond Lattice Handbag", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_chanel/product_forbrand_11.html",
	images:"../ForBrand/images/women/brand-chanel/brand-5/brand-5.jpg", type:"chanel"},
	{id:"12", name:"Braun Chanel black Satchel Handbag", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_chanel/product_forbrand_12.html",
	images:"../ForBrand/images/women/brand-chanel/brand-6/brand-6.jpg", type:"chanel"},
	
	//lv
	{id:"13", name:"YesMacton cowskin Genuine Leather Women", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_lv/product_forbrand_13.html",
	images:"../ForBrand/images/women/brand-lv/brand-1/brand-1.jpg", type:"lv"},
	{id:"14", name:"Monogram Canvas Sarah Wallet", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_lv/product_forbrand_14.html",
	images:"../ForBrand/images/women/brand-lv/brand-2/brand-2.jpg", type:"lv"},
	{id:"15", name:"Leather Accents Classic Boston Bag", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_lv/product_forbrand_15.html",
	images:"../ForBrand/images/women/brand-lv/brand-3/brand-3.jpg", type:"lv"},
	{id:"16", name:"Sharon Monogram Canvas Palm Springs Backpack Mini Handbag", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_lv/product_forbrand_16.html",
	images:"../ForBrand/images/women/brand-lv/brand-4/brand-4.jpg", type:"lv"},
	{id:"17", name:"FairyBridal Women Real Leather Cross Body Handbags", price:"$ 268.99", 
	href_product:"Product_ForBrand/product_forbrand_lv/product_forbrand_17.html",
	images:"../ForBrand/images/women/brand-lv/brand-5/brand-5.jpg", type:"lv"},
	{id:"18", name:"Ceyue Women's Drawstring Handbag Bucket Bags Shoulder Backpack", price:"$115.00", 
	href_product:"Product_ForBrand/product_forbrand_lv/product_forbrand_18.html",
	images:"../ForBrand/images/women/brand-lv/brand-6/brand-6.jpg", type:"lv"}
	
	]
app.controller('myCtrl', function($scope) {
    $scope.products = listProductObject;
});